[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dracrac"
dynamic = ["version"]
description = 'MILA DRAC RAC'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Satya Ortiz-Gagne", email = "satya.ortiz-gagne@mila.quebec" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/Satya Ortiz-Gagne/dracrac#readme"
Issues = "https://github.com/Satya Ortiz-Gagne/dracrac/issues"
Source = "https://github.com/Satya Ortiz-Gagne/dracrac"

[project.scripts]
dracrac = "dracrac.cli:dracrac"

[tool.hatch.version]
path = "src/dracrac/__about__.py"

[tool.hatch.envs.default]
detach = true
installer = "uv"
dependencies = [
  "uv==0.9.4"
]

[tool.hatch.envs.2026.scripts]
list-refs = [
  "",
  """
  cd {root:real}/src/dracrac/2026
  uv lock --script filter.py
  uv lock --script list_papers.py
  uv run --script filter.py "paperoni-2024-04-01--2025-10-09.json" --authors "profs.txt" --start "2024-04-01" --out "profs/"
  uv run --script list_papers.py --out refs/papers.json --format json profs/*.json
  uv run --script list_papers.py --out refs/papers.csv --format csv profs/*.json
  """
]
bin-venues = [
  "",
  """
  cd {root:real}/src/dracrac/2026
  uv lock --script bin_venues.py
  if [ -f "venues/bins.yaml" ]
  then
    uv run --script bin_venues.py "paperoni-2024-04-01--2025-10-09.json" --start "2024-04-01" --end "2025-04-01" --bins "venues/bins.yaml" --out "venues/bins.txt"
    cat "venues/bins.txt"
  else
    uv run --script bin_venues.py "paperoni-2024-04-01--2025-10-09.json" --start "2024-04-01" --end "2025-04-01" --out "venues/all.txt"
    for v in "International Conference on Learning Representations" \
      "ICLR" \
      "International Conference on Machine Learning" \
      "ICML" \
      "Neural Information Processing Systems" \
      "NeurIPS"
    do
      grep -i "$v" venues/all.txt >"venues/$v.txt"
      echo "venues/$v.txt"
      cat "venues/$v.txt"
    done
    echo "Please update the 'venues/bins.yaml' file by looking at the matches in 'venues/*.txt'. Then run this script again."
  fi
  """
]

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/dracrac tests}"

[tool.coverage.run]
source_pkgs = ["dracrac", "tests"]
branch = true
parallel = true
omit = [
  "src/dracrac/__about__.py",
]

[tool.coverage.paths]
dracrac = ["src/dracrac", "*/dracrac/src/dracrac"]
tests = ["tests", "*/dracrac/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
